First App/myapp/models.py
# myapp/models.py
from flask_sqlalchemy import SQLAlchemy
from flask_login import UserMixin

db = SQLAlchemy()

class User(UserMixin , db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(80), unique=True, nullable=False)
    password = db.Column(db.String(200), nullable=False)

    def __repr__(self):
        return f"<User {self.username}>"

class BlogPost(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(100), nullable=False)
    content = db.Column(db.Text, nullable=False)
    is_public = db.Column(db.Boolean, default=False)
    author_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    author = db.relationship('User', backref=db.backref('blog_posts', lazy=True))

    def __repr__(self):
        return f"<BlogPost {self.title}>"

class Todo(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    task = db.Column(db.String(200), nullable=False)
    done = db.Column(db.Boolean, default=False)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    user = db.relationship('User', backref=db.backref('todos', lazy=True))

First App/myapp/__init__.py
# myapp/__init__.py
from flask import Flask
from flask_login import LoginManager
from .models import db , User
from .auth.routes import auth
from .home.routes import home
from .blog.routes import blog
from .todo.routes import todo
from .config import Config

login_manager = LoginManager()

def create_app():
    app = Flask(__name__)
    app.config.from_object(Config)

    db.init_app(app)
    login_manager.init_app(app)
    login_manager.login_view = 'auth.login'
    
    @login_manager.user_loader
    def load_user(user_id):
        return User.query.get(int(user_id))

    app.register_blueprint(auth, url_prefix='/auth')
    app.register_blueprint(blog, url_prefix='/blog')
    app.register_blueprint(todo, url_prefix='/todo')

    app.register_blueprint(home, url_prefix='/')

    with app.app_context():
        db.create_all()  # create tables if not exist

    return app

# # This tells Flask-Login how to get a user by ID
# @login_manager.user_loader
# def load_user(user_id):
#     return User.query.get(int(user_id))

First App/myapp/blog/routes.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from flask_login import login_required, current_user
from myapp.models import db, BlogPost

blog = Blueprint('blog', __name__, template_folder='templates/blog')

@blog.route('/myblogs')
@login_required
def my_blogs():
    blogs = BlogPost.query.filter_by(author=current_user).all()
    return render_template('my_blogs.html', blogs=blogs)


@blog.route('/create', methods=['GET', 'POST'])
@login_required
def create_blog():
    if request.method == 'POST':
        title = request.form['title']
        content = request.form['content']
        is_public = 'is_public' in request.form  # checkbox presence

        new_blog = BlogPost(
            title=title,
            content=content,
            is_public=is_public,
            author=current_user
        )

        db.session.add(new_blog)
        db.session.commit()

        flash('Blog post created!', 'success')
        return redirect(url_for('blog.my_blogs'))

    return render_template('create_blog.html')


@blog.route('/delete/<int:blog_id>')
@login_required
def delete_blog(blog_id):
    blog = BlogPost.query.get_or_404(blog_id)

    if blog.author != current_user:
        flash("You can't delete another user's blog.", 'error')
        return redirect(url_for('blog.my_blogs'))

    db.session.delete(blog)
    db.session.commit()

    flash('Blog deleted successfully.', 'success')
    return redirect(url_for('blog.my_blogs'))


@blog.route('/toggle-public/<int:blog_id>')
@login_required
def toggle_public(blog_id):
    blog = BlogPost.query.get_or_404(blog_id)

    if blog.author != current_user:
        flash("You can't modify another user's blog.", 'error')
        return redirect(url_for('blog.my_blogs'))

    # Toggle public/private
    blog.is_public = not blog.is_public
    db.session.commit()

    flash('Blog visibility updated.', 'success')
    return redirect(url_for('blog.my_blogs'))


@blog.route('/blog/<int:blog_id>')
def blog_detail(blog_id):
    blog = BlogPost.query.get_or_404(blog_id)

    # Only allow owner or public blogs to be viewed
    if not blog.is_public and (not current_user.is_authenticated or blog.author != current_user):
        flash("This blog is private.", "error")
        return redirect(url_for("home.index"))

    return render_template("blog_detail.html", blog=blog)

First App/myapp/home/routes.py
# myapp/home/routes.py
from flask import Blueprint, render_template, session, redirect, url_for
from myapp.models import User , BlogPost
from flask_login import current_user

home = Blueprint('home', __name__ , template_folder='templates/home')

@home.route('/')
def index():
    public_blogs = BlogPost.query.filter_by(is_public=True).all()
    return render_template('home.html', public_blogs=public_blogs)
@home.route('/members')
def members(): 
    users = User.query.all()
    return render_template('members.html', members=[u.username for u in users])

@home.route('/test-login')
def test_login():
    if current_user.is_authenticated:
        return f"Logged in as {current_user.username}"
    else:
        return "Not logged in"

First App/myapp/todo/routes.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from flask_login import login_required, current_user
from myapp.models import db, Todo

todo = Blueprint('todo', __name__, template_folder='templates/todo')

@todo.route('/todo', methods=['GET', 'POST'])
@login_required
def index():
    if request.method == 'POST':
        task = request.form.get('task')
        if task:
            new_todo = Todo(task=task, user=current_user)
            db.session.add(new_todo)
            db.session.commit()
            flash("Task added!", "success")
        return redirect(url_for('todo.index'))

    todos = Todo.query.filter_by(user=current_user).all()
    return render_template('index.html', todos=todos)

@todo.route('/todo/toggle/<int:id>')
@login_required
def toggle(id):
    todo = Todo.query.get_or_404(id)
    if todo.user != current_user:
        flash("You can't edit another user's task.", "error")
        return redirect(url_for('todo.index'))
    todo.done = not todo.done
    db.session.commit()
    return redirect(url_for('todo.index'))

@todo.route('/todo/delete/<int:id>')
@login_required
def delete(id):
    todo = Todo.query.get_or_404(id)
    if todo.user != current_user:
        flash("You can't delete another user's task.", "error")
        return redirect(url_for('todo.index'))
    db.session.delete(todo)
    db.session.commit()
    flash("Task deleted.", "success")
    return redirect(url_for('todo.index'))

First App/myapp/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>{% block title %}BASE PAGE!!{% endblock  %}</title>
  {% block link %}{% endblock link %}
  <!-- Optional: Add any other meta tags or external resources here -->
</head>
<body>
    <style>
            .flash {
      padding: 10px 20px;
      margin: 10px auto;
      width: fit-content;
      border-radius: 5px;
      color: white;
      font-family: sans-serif;
      animation: fadeOut 4s forwards;
    }

    .flash-success { background-color:rgb(27, 208, 33); }  /* Green */
    .flash-error { background-color: #f44336; }    /* Red */
    .flash-warning { background-color: #ff9800; }  /* Orange */

    @keyframes fadeOut {
      0% { opacity: 1; }
      80% { opacity: 1; }
      100% { opacity: 0; }
      {% block style %}
        {% endblock style %}
    </style>
  <header><hr>
    {% block header %}
        <u><h1>Welcome to My Website</h1></u>
    <!-- Navigation, logo, etc. -->
     <!-- templates/base.html -->
<nav>
  <a href="{{ url_for('home.index') }}">Home</a> |
    <a href="{{ url_for('home.members') }}">Members</a> |
  {% if current_user.is_authenticated %}
    <a href="{{ url_for('blog.my_blogs') }}">My Blogs</a> |
    <a href="{{ url_for('todo.index') }}">To-Do List</a> |
    <a href="{{ url_for('auth.logout') }}">Logout</a>
    <span style="margin-left:10px;">Welcome, {{ current_user.username }}</span>
  {% else %}
    <a href="{{ url_for('auth.login') }}">Login</a>
  {% endif %}
</nav>

    {% endblock header %}
    <hr>
  </header>

    <!--  FLASH MESSAGES  -->
    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
        {% for category, message in messages %}
            <div class="flash flash-{{ category }}">{{ message }}</div>
        {% endfor %}
        {% endif %}
    {% endwith %}

    <!--  FLASH MESSAGES  -->


  <main><hr>
    {% block content %}
      <section>
      <h2>Section Title</h2>
      <p>This is a paragraph of content.</p>
    </section>
    <!-- Add more sections as needed -->
    {% endblock content %}<hr>
  </main>

  <footer> <hr>
    {% block footer %}
   
        <p>&copy; 2025 <u>RADHA VALLABH SHRI HARIVANSH</u>. All rights reserved.</p>
        
    {% endblock footer %}
    <hr>
  </footer>

  <!-- Link to external JavaScript file -->
   {% block script %}
   <!--<script src="script.js"></script>
   -->  
   {% endblock script %}
</body>
</html>