First App/myapp/blog/routes.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from flask_login import login_required, current_user
from myapp.models import db, BlogPost

blog = Blueprint('blog', __name__, template_folder='templates/blog')

@blog.route('/myblogs')
@login_required
def my_blogs():
    blogs = BlogPost.query.filter_by(author=current_user).all()
    return render_template('my_blogs.html', blogs=blogs)


@blog.route('/create', methods=['GET', 'POST'])
@login_required
def create_blog():
    if request.method == 'POST':
        title = request.form['title']
        content = request.form['content']
        is_public = 'is_public' in request.form  # checkbox presence

        new_blog = BlogPost(
            title=title,
            content=content,
            is_public=is_public,
            author=current_user
        )

        db.session.add(new_blog)
        db.session.commit()

        flash('Blog post created!', 'success')
        return redirect(url_for('blog.my_blogs'))

    return render_template('create_blog.html')


@blog.route('/delete/<int:blog_id>')
@login_required
def delete_blog(blog_id):
    blog = BlogPost.query.get_or_404(blog_id)

    if blog.author != current_user:
        flash("You can't delete another user's blog.", 'error')
        return redirect(url_for('blog.my_blogs'))

    db.session.delete(blog)
    db.session.commit()

    flash('Blog deleted successfully.', 'success')
    return redirect(url_for('blog.my_blogs'))


@blog.route('/toggle-public/<int:blog_id>')
@login_required
def toggle_public(blog_id):
    blog = BlogPost.query.get_or_404(blog_id)

    if blog.author != current_user:
        flash("You can't modify another user's blog.", 'error')
        return redirect(url_for('blog.my_blogs'))

    # Toggle public/private
    blog.is_public = not blog.is_public
    db.session.commit()

    flash('Blog visibility updated.', 'success')
    return redirect(url_for('blog.my_blogs'))


@blog.route('/blog/<int:blog_id>')
def blog_detail(blog_id):
    blog = BlogPost.query.get_or_404(blog_id)

    # Only allow owner or public blogs to be viewed
    if not blog.is_public and (not current_user.is_authenticated or blog.author != current_user):
        flash("This blog is private.", "error")
        return redirect(url_for("home.index"))

    return render_template("blog_detail.html", blog=blog)

First App/myapp/blog/templates/blog/blog_detail.html
{% extends "base.html" %}
{% block content %}
<h1>{{ blog.title }}</h1>

<hr>

<!-- Always show blog content -->
<div>
 <pre style="white-space: pre-wrap; font-family: inherit;">
{{ blog.content }}
</pre>
</div>
  <hr>

<!-- Only show edit options if user is logged in and owns the blog -->
{% if current_user.is_authenticated and blog.author == current_user %}
  <p>
    <a href="{{ url_for('blog.toggle_public', blog_id=blog.id) }}">Toggle Public/Private</a>
  </p>
  <p>
  <strong>Visibility:</strong>
  {{ 'Public' if blog.is_public else 'Private' }}
</p>


  <form action="{{ url_for('blog.delete_blog', blog_id=blog.id) }}" method="post">
    <button type="submit" onclick="return confirm('Are you sure you want to delete this blog?')">
      Delete Blog
    </button>
  </form>

  <p>
    <a href="{{ url_for('blog.my_blogs') }}">Back to My Blogs</a>  

  </p>
{% endif %}
{% endblock %}

First App/myapp/blog/templates/blog/create_blog.html
{% extends "base.html" %}
{% block content %}
<h1>Create New Blog</h1>
<form method="post">
  <label>Title:</label><br>
  <input type="text" name="title" required><br><br>

  <label>Content:</label><br>
  <textarea name="content" rows="5" required></textarea><br><br>

  <label><input type="checkbox" name="is_public"> Make Public</label><br><br>

  <button type="submit">Create Blog</button>
</form>
{% endblock %}

First App/myapp/blog/templates/blog/my_blogs.html
{% extends "base.html" %}
{% block content %}
<u><h1>My Blogs</h1></u>

<a href="{{ url_for('blog.create_blog') }}">Create New Blog</a>
<ul>
  {% for blog in blogs %}<hr>
  <li>
    <u><strong>{{ blog.title }}</strong></u>
    ({{ 'Public' if blog.is_public else 'Private' }})
    - <a href="{{ url_for('blog.toggle_public', blog_id=blog.id) }}">Toggle Visibility</a>
    - <a href="{{ url_for('blog.delete_blog', blog_id=blog.id) }}" onclick="return confirm('Delete this blog?')">Delete</a>
    - <a href="{{ url_for('blog.blog_detail', blog_id=blog.id) }}">View Details</a>
    <p>{{ blog.content[:500] }}...</p> <!-- Truncate content to 100 characters -->
  </li><hr>
  {% endfor %}
</ul>
{% endblock %}